// SPDX-FileCopyrightText: 2026 Greyfoundry contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { checkPublicProvenance } from './check-public-provenance.mjs';

const assembled = (...parts) => parts.join('');

async function withTrackedFiles(files, callback) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'elah-public-provenance-'));
  try {
    execFileSync('git', ['init', '--quiet'], { cwd: root });
    for (const [relativePath, contents] of Object.entries(files)) {
      const absolutePath = path.join(root, relativePath);
      await mkdir(path.dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, contents);
    }
    execFileSync('git', ['add', '.'], { cwd: root });
    await callback(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test('rejects public documentation that names hidden authorship provenance', async () => {
  const namedModel = assembled('Chat', 'GPT');
  await withTrackedFiles(
    { 'README.md': `# Example\n\nGenerated by ${namedModel}.\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'README.md:3: public provenance policy violation: automated authorship claim',
        'README.md:3: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('rejects tool provenance markers in source comments', async () => {
  const namedTool = assembled('Code', 'x');
  await withTrackedFiles(
    { 'src/example.mjs': `// Created with ${namedTool}\nexport const value = 1;\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'src/example.mjs:1: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('scans the provenance scanner and its tests like every other public file', async () => {
  const namedTool = assembled('Code', 'x');
  await withTrackedFiles(
    { 'scripts/ci/check-public-provenance.test.mjs': `// Created with ${namedTool}\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'scripts/ci/check-public-provenance.test.mjs:1: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('rejects generic automated authorship formulations', async () => {
  const claims = [
    ['agent', 'authored'].join('-'),
    ['AI', 'assisted'].join('-'),
    ['LLM', 'generated'].join('-'),
  ];
  await withTrackedFiles(
    { 'NOTICE.txt': claims.map((claim) => `This file is ${claim}.`).join('\n') },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'NOTICE.txt:1: public provenance policy violation: automated authorship claim',
        'NOTICE.txt:2: public provenance policy violation: automated authorship claim',
        'NOTICE.txt:3: public provenance policy violation: automated authorship claim',
      ]);
    },
  );
});

test('rejects additional named model and tool attributions', async () => {
  const names = [
    assembled('Co', 'pilot'),
    assembled('Cur', 'sor'),
    assembled('Gem', 'ini'),
  ];
  await withTrackedFiles(
    { 'NOTICE.txt': names.map((name) => `Created with ${name}.`).join('\n') },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'NOTICE.txt:1: public provenance policy violation: named model or tool',
        'NOTICE.txt:2: public provenance policy violation: named model or tool',
        'NOTICE.txt:3: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('allows neutral machine-generated artifact notices', async () => {
  await withTrackedFiles(
    { 'src/generated.java': '// Generated by the pinned protobuf compiler. DO NOT EDIT.\n' },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), []);
    },
  );
});
