// ╔══════════════════════════════════════════════════════════════════╗
// ║                                                                  ║
// ║                   ELAH — A GREYFOUNDRY PROJECT                   ║
// ║                                                                  ║
// ║               https://github.com/greyfoundry/elah                ║
// ║                                                                  ║
// ╚══════════════════════════════════════════════════════════════════╝
//
// Copyright © 2026 Greyfoundry contributors.
// SPDX-FileCopyrightText: 2026 Greyfoundry contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { checkPublicProvenance } from './check-public-provenance.mjs';

const assembled = (...parts) => parts.join('');

async function withTrackedFiles(files, callback) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'elah-public-provenance-'));
  try {
    execFileSync('git', ['init', '--quiet'], { cwd: root });
    for (const [relativePath, contents] of Object.entries(files)) {
      const absolutePath = path.join(root, relativePath);
      await mkdir(path.dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, contents);
    }
    execFileSync('git', ['add', '.'], { cwd: root });
    await callback(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test('rejects public documentation that names hidden authorship provenance', async () => {
  const namedModel = assembled('Chat', 'GPT');
  await withTrackedFiles(
    { 'README.md': `# Example\n\nGenerated by ${namedModel}.\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'README.md:3: public provenance policy violation: automated authorship claim',
        'README.md:3: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('rejects tool provenance markers in source comments', async () => {
  const namedTool = assembled('Code', 'x');
  await withTrackedFiles(
    { 'src/example.mjs': `// Created with ${namedTool}\nexport const value = 1;\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'src/example.mjs:1: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('scans the provenance scanner and its tests like every other public file', async () => {
  const namedTool = assembled('Code', 'x');
  const genericClaim = ['AI', 'authored'].join('-');
  await withTrackedFiles(
    {
      'scripts/ci/check-public-provenance.test.mjs': `// Created with ${namedTool}\n// ${genericClaim} release notes\n`,
    },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'scripts/ci/check-public-provenance.test.mjs:1: public provenance policy violation: named model or tool',
        'scripts/ci/check-public-provenance.test.mjs:2: public provenance policy violation: automated authorship claim',
      ]);
    },
  );
});

test('rejects generic automated authorship formulations', async () => {
  const claims = [
    ['agent', 'authored'].join('-'),
    ['AI', 'assisted'].join('-'),
    ['LLM', 'generated'].join('-'),
  ];
  await withTrackedFiles(
    { 'NOTICE.txt': claims.map((claim) => `This file is ${claim}.`).join('\n') },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'NOTICE.txt:1: public provenance policy violation: automated authorship claim',
        'NOTICE.txt:2: public provenance policy violation: automated authorship claim',
        'NOTICE.txt:3: public provenance policy violation: automated authorship claim',
      ]);
    },
  );
});

test('rejects additional named model and tool attributions', async () => {
  const names = [
    assembled('Co', 'pilot'),
    assembled('Cur', 'sor'),
    assembled('Gem', 'ini'),
  ];
  await withTrackedFiles(
    { 'NOTICE.txt': names.map((name) => `Created with ${name}.`).join('\n') },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'NOTICE.txt:1: public provenance policy violation: named model or tool',
        'NOTICE.txt:2: public provenance policy violation: named model or tool',
        'NOTICE.txt:3: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('rejects an additional generic automated authorship formulation', async () => {
  const claim = ['AI', 'authored'].join('-');
  await withTrackedFiles(
    { 'release-notes.md': `${claim} release notes.\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'release-notes.md:1: public provenance policy violation: automated authorship claim',
      ]);
    },
  );
});

test('allows an ambiguous tool name in ordinary CSS syntax', async () => {
  const property = assembled('cur', 'sor');
  await withTrackedFiles(
    { 'web/button.css': `button { ${property}: pointer; }\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), []);
    },
  );
});

test('rejects an ambiguous tool name in attribution context', async () => {
  const namedTool = assembled('Cur', 'sor');
  await withTrackedFiles(
    { 'NOTICE.txt': `Authored with ${namedTool}.\n` },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'NOTICE.txt:1: public provenance policy violation: named model or tool',
      ]);
    },
  );
});

test('allows neutral machine-generated artifact notices', async () => {
  await withTrackedFiles(
    { 'src/generated.java': '// Generated by the pinned protobuf compiler. DO NOT EDIT.\n' },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), []);
    },
  );
});
