// SPDX-FileCopyrightText: 2026 Greyfoundry contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { checkPublicProvenance } from './check-public-provenance.mjs';

async function withTrackedFiles(files, callback) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'elah-public-provenance-'));
  try {
    execFileSync('git', ['init', '--quiet'], { cwd: root });
    for (const [relativePath, contents] of Object.entries(files)) {
      const absolutePath = path.join(root, relativePath);
      await mkdir(path.dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, contents);
    }
    execFileSync('git', ['add', '.'], { cwd: root });
    await callback(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test('rejects public documentation that names hidden authorship provenance', async () => {
  await withTrackedFiles(
    { 'README.md': '# Example\n\nGenerated by ChatGPT.\n' },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'README.md:3: public provenance marker is forbidden: ChatGPT',
        'README.md:3: public provenance marker is forbidden: generated by AI',
      ]);
    },
  );
});

test('rejects tool provenance markers in source comments', async () => {
  await withTrackedFiles(
    { 'src/example.mjs': '// Created with Codex\nexport const value = 1;\n' },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), [
        'src/example.mjs:1: public provenance marker is forbidden: Codex',
      ]);
    },
  );
});

test('allows neutral machine-generated artifact notices', async () => {
  await withTrackedFiles(
    { 'src/generated.java': '// Generated by the pinned protobuf compiler. DO NOT EDIT.\n' },
    async (root) => {
      assert.deepEqual(await checkPublicProvenance(root), []);
    },
  );
});
